Ping All Hosts- 
ansible all -m ping

Create a Directory
ansible all -m file -a "path=/tmp/demo_dir state=directory mode=0755"

Create a File
ansible all -m file -a "path=/tmp/myfile.txt state=touch"

Delete a File/Directory
ansible all -m file -a "path=/tmp/demo_dir state=absent"

Create a User
ansible all -m user -a "name=devuser state=present"

 Add User to Sudoers
 ansible all -m user -a "name=devuser groups=sudo append=yes"

 Install a Package (e.g. Apache)
 ansible all -m apt -a "name=apache2 state=present update_cache=yes" -b

 Restart a Service
 ansible all -m service -a "name=apache2 state=restarted" -b

 Check Disk Space
 ansible all -a "df -h"

 Gather Facts
 ansible all -m setup

 Copy a File
 ansible all -m copy -a "src=/etc/hosts dest=/tmp/hosts_copy"

 Write Content to a File
 ansible all -m copy -a "content='Welcome to Ansible!' dest=/tmp/welcome.txt"

 Remove a User
 ansible all -m user -a "name=devuser state=absent remove=yes"

 Change File Permissions
 ansible all -m file -a "path=/tmp/welcome.txt mode=0644"

 List All Hosts in an Inventory Group
 ansible webservers --list-hosts

 Run Commands with Elevated Privileges
  ansible all -m shell -a "systemctl restart nginx" -b

Check Uptime
ansible all -a "uptime"

Test DNS or Network Connectivity
ansible all -a "ping -c 3 google.com"


Get Hostname
ansible all -a "hostname"

Fetch Files from Remote to Local (using fetch)
ansible all -m fetch -a "src=/var/log/syslog dest=/tmp/syslog flat=yes

Unarchive (Extract tar/gz files)
ansible all -m unarchive -a "src=/tmp/app.tar.gz dest=/opt/ remote_src=yes"


