---
- name: start and enable apache
  hosts: servers
  become:

  tasks:
   - name: Ensure apache is running
     service:                           #   module
      name: apache2
      state: started
      enabled: yes

